name = "jokebox"
compatibility_date = "2025-10-30"

[assets]
directory = "./dist"

[[routes]]
pattern = "jokebox.pl/*"

# Environment variables for Turnstile
[env.production.vars]
# These will be set via Cloudflare dashboard or wrangler secret:
# wrangler secret put TURNSTILE_SECRET_KEY --env production